### ISSUE TITLE
Package name change

### ISSUE THREAD

**Issue by networkmaster** [lboynton/puppet-r1soft-cdp-agent#3]
After R1Soft became Idera, they changed the package names.

This seems to be ok when installing manually through yum as it follows, but the module for puppet seems to have a issue:

Error: Could not find package r1soft-cdp-enterprise-agent
Error: /Stage[main]/R1soft_cdp_agent::Packages/Package[r1soft-cdp-enterprise-agent]/ensure: change from absent to present failed: Could not find package r1soft-cdp-enterprise-agent

Yet, when you do a lookup, it is installed:
[root@monitoring ~]# yum list installed | grep agent
serverbackup-agent.x86_64                5.4.0-32                      installed
serverbackup-async-agent-2-6.x86_64      5.4.0-32                      installed
serverbackup-enterprise-agent.x86_64     5.4.0-32                      installed
[root@monitoring ~]#

I resolved this by doing a find and replace:
grep -iR r1soft-cdp-enterprise-agent *
Changed it to the correct name and it seemed to work

**Comment by lboynton** [comment]
Do you want to make a pull request?

**Comment by networkmaster** [comment]
Err, I'm not that familiar with Git so I would probably end up breaking something :)

I also wanted to suggest renaming the R1soft names to Idera or Server Backup, they seem to be phasing out the R1Soft name altogether

**Comment by anthonysomerset** [comment]
i should note this also changed the actual class names as well, that may well need to be checked or a note added in the readme

**Comment by lboynton** [comment]
Nice work @anthonysomerset! Will check this soon.

**Comment by lboynton** [comment]
Fixed, closing.
